In [2]:
import numpy as np

In [3]:
# Numpy = Numeric Python
# ndarray = n-dim array

In [4]:
np1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np1.shape # gives the number of items

(10,)

In [11]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np4 = np.zeros(10)

In [15]:
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np5 = np.zeros((2, 10))

In [21]:
np5

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
np6 = np.full((10), 6)

In [23]:
np6

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [24]:
# Multidimensional Full
np7 = np.full((2, 6), 10)

In [25]:
np7

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [26]:
my_list = [1, 2, 3, 4]

In [27]:
np8 = np.array(my_list)

In [28]:
np8

array([1, 2, 3, 4])

In [29]:
np8[1]

2