In [1]:
import numpy as np

In [2]:
char1, char2 = ord('A'), ord('Z')

In [3]:
inputArray = np.array([ [char1, char1],
                        [char1, char2],
                        [char2, char1],
                        [char2, char2]])

### The input array is this: 

In [20]:
inputArray

array([[65, 65],
       [65, 90],
       [90, 65],
       [90, 90]])

In [21]:
targetArray = [0, 1, 1, 0]

### TargetArray

In [22]:
targetArray

[0, 1, 1, 0]

In [25]:
layer1_2Weights = np.ones((2, 2))

### Layer 1-2 weights: 

In [26]:
layer1_2Weights

array([[1., 1.],
       [1., 1.]])

In [36]:
layer2_ip = np.dot(np.array(np.transpose(inputArray[0])), layer1_2Weights)

### Layer 2-3 weights:

In [37]:
layer2_3Weights = np.ones((1, 2))

In [38]:
layer2_3Weights

array([[1., 1.]])

In [ ]:
layer3_ip = np.dot(layer2_ip