In [3]:
import numpy as np

In [4]:
input_array = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# AND Gate

#### input array

In [5]:
input_array

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [14]:
target_array = np.array([0, 0, 0, 1])

#### target array

In [15]:
target_array

array([0, 0, 0, 1])

In [16]:
weights = np.ones((2))

#### weights

In [17]:
weights

array([1., 1.])

In [ ]:
output_array = []

In [31]:
for vector in input_array:
    print(type(np.dot(vector, weights).tolist()))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
